Add regkey files to install dir for blocking CH340 driver updates
SlimeVR/SlimeVR-Installer pull request #45
Opened 2023-08-13 06:28 UTC by kounocom

Adds a few regkey files to the installation directory if CH340 drivers are selected. These are needed for some people running D1 minis, as the CH340s on those are often counterfeit and refuse to work with 2023 drivers, and Windows will constantly try to install those over the ones provided in this installer.

2023-08-13 17:25 UTC, ImUrX requested changes

2023-08-13 17:25 UTC, ImUrX commented on windows/web/fix_ch340.ps1
> +$DriverZipUrl = 'cdn.kouno.xyz/YZSvN1b5.zip'
i agree we need to change this, I suggest uploading it to Github and use their CDN

2023-08-13 17:56 UTC, ImUrX commented on windows/web/fix_ch340.ps1
> +$DriverZipUrl = 'cdn.kouno.xyz/YZSvN1b5.zip'
Or just use a bundled file lol

2023-08-13 18:59 UTC, kounocom commented
no more downloading stuff

2023-08-18 21:41 UTC, kounocom commented
after a few days of everything working, the driver stopped registering to my CH340 because of the registry changes, needs more testing

2023-11-03 07:51 UTC, closed without merging